//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfFacturacionClienteWindows.WcfFacturacion {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/WcfFacturacion")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDProducto {
            get {
                return this.IDProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.IDProductoField, value) != true)) {
                    this.IDProductoField = value;
                    this.RaisePropertyChanged("IDProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notas {
            get {
                return this.NotasField;
            }
            set {
                if ((object.ReferenceEquals(this.NotasField, value) != true)) {
                    this.NotasField = value;
                    this.RaisePropertyChanged("Notas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfFacturacion.IServicioFacturacion")]
    public interface IServicioFacturacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFacturacion/GetProducto", ReplyAction="http://tempuri.org/IServicioFacturacion/GetProductoResponse")]
        WcfFacturacionClienteWindows.WcfFacturacion.Producto GetProducto(string IDProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFacturacion/GetProducto", ReplyAction="http://tempuri.org/IServicioFacturacion/GetProductoResponse")]
        System.Threading.Tasks.Task<WcfFacturacionClienteWindows.WcfFacturacion.Producto> GetProductoAsync(string IDProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFacturacion/GetProductos", ReplyAction="http://tempuri.org/IServicioFacturacion/GetProductosResponse")]
        WcfFacturacionClienteWindows.WcfFacturacion.Producto[] GetProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFacturacion/GetProductos", ReplyAction="http://tempuri.org/IServicioFacturacion/GetProductosResponse")]
        System.Threading.Tasks.Task<WcfFacturacionClienteWindows.WcfFacturacion.Producto[]> GetProductosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioFacturacionChannel : WcfFacturacionClienteWindows.WcfFacturacion.IServicioFacturacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioFacturacionClient : System.ServiceModel.ClientBase<WcfFacturacionClienteWindows.WcfFacturacion.IServicioFacturacion>, WcfFacturacionClienteWindows.WcfFacturacion.IServicioFacturacion {
        
        public ServicioFacturacionClient() {
        }
        
        public ServicioFacturacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioFacturacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioFacturacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioFacturacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfFacturacionClienteWindows.WcfFacturacion.Producto GetProducto(string IDProducto) {
            return base.Channel.GetProducto(IDProducto);
        }
        
        public System.Threading.Tasks.Task<WcfFacturacionClienteWindows.WcfFacturacion.Producto> GetProductoAsync(string IDProducto) {
            return base.Channel.GetProductoAsync(IDProducto);
        }
        
        public WcfFacturacionClienteWindows.WcfFacturacion.Producto[] GetProductos() {
            return base.Channel.GetProductos();
        }
        
        public System.Threading.Tasks.Task<WcfFacturacionClienteWindows.WcfFacturacion.Producto[]> GetProductosAsync() {
            return base.Channel.GetProductosAsync();
        }
    }
}
