//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEF.Backend.BussinesEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPM_Clientes
    {
        public int IDCliente { get; set; }
        public string Telefono { get; set; }
        public int UltimaLectura { get; set; }
        public bool Leido { get; set; }
    }
}
