//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://Servicio", ConfigurationName="IVecindad")]
public interface IVecindad
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Servicio/IVecindad/AgregarVecino", ReplyAction="http://Servicio/IVecindad/AgregarVecinoResponse")]
    string AgregarVecino(string nombre);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Servicio/IVecindad/AgregarVecino", ReplyAction="http://Servicio/IVecindad/AgregarVecinoResponse")]
    System.Threading.Tasks.Task<string> AgregarVecinoAsync(string nombre);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Servicio/IVecindad/ListaVecinos", ReplyAction="http://Servicio/IVecindad/ListaVecinosResponse")]
    string[] ListaVecinos();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Servicio/IVecindad/ListaVecinos", ReplyAction="http://Servicio/IVecindad/ListaVecinosResponse")]
    System.Threading.Tasks.Task<string[]> ListaVecinosAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IVecindadChannel : IVecindad, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class VecindadClient : System.ServiceModel.ClientBase<IVecindad>, IVecindad
{
    
    public VecindadClient()
    {
    }
    
    public VecindadClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public VecindadClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public VecindadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public VecindadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string AgregarVecino(string nombre)
    {
        return base.Channel.AgregarVecino(nombre);
    }
    
    public System.Threading.Tasks.Task<string> AgregarVecinoAsync(string nombre)
    {
        return base.Channel.AgregarVecinoAsync(nombre);
    }
    
    public string[] ListaVecinos()
    {
        return base.Channel.ListaVecinos();
    }
    
    public System.Threading.Tasks.Task<string[]> ListaVecinosAsync()
    {
        return base.Channel.ListaVecinosAsync();
    }
}
